version: "3.6"

services:
  server:
    image: node:16
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    working_dir: /app
    depends_on:
      - db
    command: "npm run dev"

  client:
    image: node:16
    ports:
      - "3000:3000"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    command: "npm run client"
    
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: test_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mgldefi
      MYSQL_ROOT_PASSWORD: mglFuture7@$
      MYSQL_HOST: test_db

